version: '3.8'

services:

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres/init-tables.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./postgres/init-constraints.sql:/docker-entrypoint-initdb.d/02-init.sql
      - ./postgres/init-func.sql:/docker-entrypoint-initdb.d/03-init.sql
      - ./postgres/init-triggers.sql:/docker-entrypoint-initdb.d/04-init.sql
      - ./postgres/init-index.sql:/docker-entrypoint-initdb.d/05-init.sql
      - ./postgres/init-procedure.sql:/docker-entrypoint-initdb.d/06-init.sql
      - ./postgres/init-inserts.sql:/docker-entrypoint-initdb.d/07-init.sql
      - postgresdata:/var/lib/postgresql/data
      # добавить, если хотим изменить пароли пользователей на 1234567
      - ./postgres/init-pass.sql:/docker-entrypoint-initdb.d/08-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    logging:
      driver: none
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=user@test.ru
      - PGADMIN_DEFAULT_PASSWORD=1111
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8082:80
    depends_on:
      - postgres
    logging:
      driver: none
    restart: always

  backend:
    container_name: calendar-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: b5Y4ZkSHTyXGvDh/wpxyNrYLdNzZLqkhLsi1gAMwtApLlNKbHGPjto3Y6TDCVz7vV6sQuF+R5hjCUX6JE6LGlQ==
      JWT_EXPIRATION: 360000
      SERVICE_CALENDAR_URL: https://isdayoff.ru/api/getdata?year=%d&pre=1
      JAVA_OPTS: -Xmx512m -Xms256m
    depends_on:
      - postgres

volumes:

  postgresdata:
    driver: local

  pgadmindata:
    driver: local

